### ISSUE TITLE
React Upload Widget: Delay on first upload 

### ISSUE THREAD

**Issue by koren3210** [colbyfayock/cloudinary-examples#6]
Hey I tried this is my project and even with this project. It seems like it take few second for the widget to open. I open the dev tools and the action of open the I frame element take few seconds.

**Comment by colbyfayock** [comment]
hey @koren3210 which example are you looking at?

assuming you're looking at the React example, I've added a requiredIdleCallback inside of the UploadWidget component which I think greatly improves the experience, though i haven't tested it further from a performance perspective in terms of loading the widget before interaction beyond using the browser's idle designation

https://github.com/colbyfayock/cloudinary-examples/blob/main/examples/react-upload-widget-preset/src/components/UploadWidget/UploadWidget.js#L15

https://cloudinary-react-upload-widget-preset.netlify.app/

thoughts?

**Comment by koren3210** [comment]
tank you for the response @colbyfayock .
yes i looked at the react example.
now it work better. 

other issue: 
when i navigate between pages in my react app it open a new widget.

<img width="492" alt="Screen Shot 2023-02-03 at 22 13 41" src="https://user-images.githubusercontent.com/85394450/216702214-dd87194b-9a5e-40db-be50-cf850f7b894f.png">

**Comment by colbyfayock** [comment]
i'm not sure at what point of the lifecycle that happens, but i wonder if that can be resolved by lifting the refs of cloudinary and the widget outside of the widget component function

for instance, intsead of:
```
const UploadWidget = ({ children, onUpload }) => {
  const cloudinary = useRef();
  const widget = useRef();
```

we could try:

```
let cloudinary;
let widget;

const UploadWidget = ({ children, onUpload }) => {
```

then instead of storing the widget on the ref, we would store it in that variable:

```
    requestIdleCallback(() => {
      if ( !widget ) {
        widget = createWidget();
      }
    });
```

you would need to make that change for any instance that's using the original refs

want to give that a try?

**Comment by koren3210** [comment]
tank you @colbyfayock  
it tried it and it work great

**Comment by koren3210** [comment]
@JoshuaRotimi hey this is why the variables are outside the function
